version: "2"
linters:
  enable-all: true
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # we can manage dependencies strictly if the need arises in the future
    - err113            # internal error causes may be dynamic
    - exhaustruct       # don't _always_ need to exhaustively create struct
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - gomoddirectives   # we use go modules replacements intentionally
    - gomodguard        # not compatible with go workspaces
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - musttag           # incompatible with go workspaces
    - nlreturn          # generous whitespace violates house style
    - nonamedreturns    # usage of named returns should be selective
    - tenv              # deprecated: replaced by usetesting
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # over-generous whitespace violates house style
linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [ FIXME ]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
      - ok bool
      - w io.Writer
issues:
  exclude-use-default: true
  exclude-rules:
    # Loosen requirements on tools
    - path: tools/
      linters:
        - gosec
        - forbidigo
    # gci is confused by "slices" and suggests to move it to the end of the import list
    - path: tools/protovalidate-conformance/internal/results/result.go
      linters:
        - gci
    # Building the conformance test suites
    - path: tools/protovalidate-conformance/internal/cases/
      linters:
        - funlen
        - maintidx
        - mnd
        - dupl
        - gosmopolitan
    # Loosen requirements on tests
    - path: _test.go
      linters:
        - funlen
        - varnamelen
        - unparam
        - gosec
