name: Bazel
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
  pull-requests: write
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [legacy, bzlmod]
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-${{ matrix.type }}
          repository-cache: true
      - if: matrix.type == 'legacy'
        name: Test Bazel targets with legacy WORKSPACE mode
        run: bazel build --reuse_sandbox_directories --noenable_bzlmod --enable_workspace //... && bazel test --noenable_bzlmod --enable_workspace //...
      - if: matrix.type == 'bzlmod'
        name: Test Bazel targets with bzlmod-only mode
        run: bazel build --reuse_sandbox_directories --enable_bzlmod --noenable_workspace //... && bazel test --enable_bzlmod --noenable_workspace //...
      - if: matrix.type == 'bzlmod'
        name: Test Bazel targets with defaults
        # default behavior is hybrid: bzlmod and workspace enabled
        run: bazel build --reuse_sandbox_directories //... && bazel test //...
