name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    if: github.repository == 'bufbuild/protovalidate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: bufbuild/buf-action@v1
        with:
          version: "1.72.0"
          token: ${{ secrets.BUF_TOKEN }}
          push: ${{ github.ref != 'refs/heads/main' && github.event_name == 'push' }}
