name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
  pull-requests: write
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Install go
        uses: actions/setup-go@v6
        with:
          go-version-file: tools/go.mod
          cache-dependency-path: go.work.sum
      - name: Install buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Buf generate
        run: |
          mkdir -p .tmp/bin
          cp $(which buf) .tmp/bin/buf
          make checkgenerate
      - run: make test-go
      - run: make lint-go
