# Copyright 2023-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish to BCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g. "v1.0.0")'
        required: true

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.4.2
    with:
      draft: false
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      registry_fork: bufbuild/bazel-central-registry
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
